package theme

const (
	Blue         string = "blue"
	Blue2        string = "blue2"
	Blue3        string = "blue3"
	BlueMarble   string = "blue-marble"
	Canvas       string = "canvas"
	Wood         string = "wood"
	Wood2        string = "wood2"
	Wood3        string = "wood3"
	Wood4        string = "wood4"
	Maple        string = "maple"
	Maple2       string = "maple2"
	Brown        string = "brown"
	Leather      string = "leather"
	Green        string = "green"
	Marble       string = "marble"
	GreenPlastic string = "green-plastic"
	Grey         string = "grey"
	Metal        string = "metal"
	Olive        string = "olive"
	Newspaper    string = "newspaper"
	Purple       string = "purple"
	PurpleDiag   string = "purple-diag"
	Pink         string = "pink"
	Ic           string = "ic"
)
