package piece

const (
	Cburnett    string = "cburnett"
	Merida      string = "merida"
	Alpha       string = "alpha"
	Pirouetti   string = "pirouetti"
	Chess7      string = "chess7"
	Reillycraig string = "reillycraig"
	Companion   string = "companion"
	Riohacha    string = "riohacha"
	Kosal       string = "kosal"
	Leipzig     string = "leipzig"
	Fantasy     string = "fantasy"
	Spatial     string = "spatial"
	California  string = "california"
	Pixel       string = "pixel"
	Maestro     string = "maestro"
	Fresca      string = "fresca"
	Cardinal    string = "cardinal"
	Gioco       string = "gioco"
	Tatiana     string = "tatiana"
	Staunty     string = "staunty"
	Governor    string = "governor"
	Dubrovny    string = "dubrovny"
	Icpieces    string = "icpieces"
	Shapes      string = "shapes"
	Letter      string = "letter"
)
